DROP DATABASE IF EXISTS company;
CREATE DATABASE company;
USE company;

CREATE TABLE departments (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE roles (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  departments_id INTEGER NOT NULL,
  CONSTRAINT fk_departments 
    FOREIGN KEY (departments_id) 
    REFERENCES departments (id)
    ON DELETE SET NULL
);

CREATE TABLE employees (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  roles_id INTEGER NOT NULL,
  manager_id INTEGER NOT NULL,
  CONSTRAINT fk_roles 
    FOREIGN KEY (roles_id) 
    REFERENCES roles (id)
    ON DELETE SET NULL
);

